### ISSUE TITLE
grv function used by NST assumes wrong argument

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ccpp-physics#130]
# Description

The NST model uses the function ``grv`` to give the latitude dependence of gravity. 

https://github.com/ufs-community/ccpp-physics/blob/c2ec9e5e165dac07a991424bd22bb0667cf32017/physics/module_nst_water_prop.f90#L485-L500

This function assumes the argument is the latitude but the value actually used by ``sfc_nst.f`` is the sin(latitude).

https://github.com/ufs-community/ccpp-physics/blob/c2ec9e5e165dac07a991424bd22bb0667cf32017/physics/sfc_nst.f#L372

## Additional Context

See [gravity forumla 1980](http://www-gpsg.mit.edu/~tah/12.221_2005/grs80_corr.pdf) for the definition of gravity=f(latitude) used in this module.

**Comment by junwang-noaa** [comment]
Thanks to Denise for this bug fix. @yangfanglin @Qingfu-Liu @XuLi-NOAA FYI. Also would you like to do some testing to see the impact of this bug fix?

**Comment by yangfanglin** [comment]
maybe start with comparing results between two regression tests ?  @XuLi-NOAA

**Comment by XuLi-NOAA** [comment]
> maybe start with comparing results between two regression tests ? @XuLi-NOAA

I can do that once these two regression tests are available (or already, juts point them to me). As I understand, it purly/only affects the latittude dependent gravity accelaration variation, as Denise pointed, at 45 degree, the error due the bug is about 0.26%. And the impact of this parameter (g) on the NSST model must be very limited.

**Comment by yangfanglin** [comment]
@XuLi-NOAA  making a few plots of NSST related variables and posting here should suffice for closing this PR
