### ISSUE TITLE
Possible bug in GFS_diagnostics.F90, instantaneous versus accumulated short/longwave upward-directed, TOA

### ISSUE THREAD

**Issue by gthompsnWRF** [ufs-community/ccpp-physics#39]
# Description

In my simulation, I am attempting to use the `diag_table` to output values of **instantaneous** (not time-average or accumulated) top-of-atmosphere outgoing (upward directed) shortwave and longwave radiation.  The variables `USWRFItoa` and `ULWRFItoa` are clearly growing larger during my simulation appearing like accumulations, not instantaneous.

I definitely need to see instantaneous, not time averaged values and the two relevant sections of code are lines 302-326 for what is labeled as instantaneous and lines 579-607 for time-averaged.  The two sections differ only by taking the time-averaging lines found in the latter section and not present in the former section.

The instantaneous upward-directed SW/LW radiation fluxes from surface are easy to locate in the file, but why not have TOA values as well, or have I missed them somewhere?

**Comment by grantfirl** [comment]
Hi @gthompsnWRF. I think that this issue probably belongs as an issue in the https://github.com/NOAA-EMC/fv3atm repo, since you're referencing a file there. I see that the GFS_diagnostics.F90 file is in the ccpp/driver directory for some reason, but it isn't directly related to the CCPP.

Having said that, it seems to me that `USWRFItoa` and `ULWRFItoa` are just labeled incorrectly in GFS_diagnostics.F90. Yes, those variables don't have `time_avg = .TRUE.`, so they're "instantaneous" in that sense, but the variables that are being written out are actually accumulated every radiation timestep until the diagnostic "buckets" are emptied (see, e.g. ccpp/physics/physics/GFS_rrtmg_post.F90/GFS_rrtmg_post_run and look for `fluxr(i,1 )` or `fluxr(i,2 )`. 

It looks like the actual instantaneous values that you're looking for have names of `sw_upfxc` and `lw_upfxc` in GFS_diagnostics.F90.

If this answer is insufficient, we should probably transfer this issue to fv3atm.

**Comment by gthompsnWRF** [comment]
@grantfirl  Thank you, that helps a LOT.  I had searched for variables with "toa" in the comments or variable names and missed these.  I should have broadened my search with other strings.

I consider this issue closed but you can decide if the file needs to be moved away from `ccpp/driver`.

Thanks.
